{% set version = "1.6.1" %}

package:
  name: shapelib
  version: {{ version }}

source:
  url: http://download.osgeo.org/shapelib/shapelib-{{ version }}.tar.gz
  sha256: 5da90a60e25440f108f4e8e95732bfa83ede13c8e0c2bcf80ae41006cc8ebc20

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('shapelib', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libshp${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\shp.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\shp.dll exit 1  # [win]

about:
  home: http://shapelib.maptools.org/
  license: MIT
  license_file: COPYING
  summary: Reading, writing and updating of ESRI Shapefiles
  description: |
    The Shapefile C Library provides the ability to write simple C programs for
    reading, writing and updating (to a limited extent) ESRI Shapefiles,
    and the associated attribute file (.dbf).

extra:
  recipe-maintainers:
    - kmuehlbauer
    - hobu
