{% set name = "shapelib" %}
{% set version = "1.4.1" %}
{% set sha256 = "a4c94817365761a3a4c21bb3ca1c680a6bdfd3edd61df9fdd291d3e7645923b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://download.osgeo.org/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

  run:

test:
  commands:
    - test -e $PREFIX/lib/libshp.so  # [linux]
    - test -e $PREFIX/lib/libshp.dylib  # [osx]
    - if not exist %LIBRARY_LIB%\\shp.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\shp.dll exit 1  # [win]

about:
  home: http://shapelib.maptools.org/
  license: MIT
  summary: 'Reading, writing and updating of ESRI Shapefiles'
  description: |
    The Shapefile C Library provides the ability to write simple C programs for
    reading, writing and updating (to a limited extent) ESRI Shapefiles,
    and the associated attribute file (.dbf).

extra:
  recipe-maintainers:
    - kmuehlbauer
